services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./templates-html:/usr/share/nginx/html/ 
    ports:
    - "5000:80"
    - "5001:8090"
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - SERVER_NAME=${SERVER_NAME}